name: Deploy

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
on:
  push:
    branches: ['main']

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/book-rpg-api/
            git pull origin main
            git status
            docker container stop book-rpg-api
            docker container rm book-rpg-api
            docker image rm book-rpg-api
            docker build -t book-rpg-api .
            docker run -d --name book-rpg-api -p 3000:3000 book-rpg-api
